"use client";
import { useEffect, useRef, useState } from "react";

const findings = [["Hydration appearance",72],["Visible pores",38],["Pigmentation",24]];
export default function Home(){
 const [step,setStep]=useState(1),[booked,setBooked]=useState(false),[time,setTime]=useState("10:30 AM");
 const [cameraActive,setCameraActive]=useState(false),[photoUrl,setPhotoUrl]=useState<string|null>(null),[cameraError,setCameraError]=useState("");
 const videoRef=useRef<HTMLVideoElement|null>(null),streamRef=useRef<MediaStream|null>(null);
 const stopCamera=()=>{streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;setCameraActive(false)};
 const clearPhoto=()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);setPhotoUrl(null)};
 const startCamera=async()=>{setCameraError("");clearPhoto();try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("Camera is not supported in this browser.");const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:1280}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCameraActive(true)}catch(error){stopCamera();setCameraError(error instanceof Error&&error.name==="NotAllowedError"?"Camera permission was denied. Please allow camera access in your browser settings.":error instanceof Error?error.message:"Unable to open the camera.")}};
 const capturePhoto=()=>{const video=videoRef.current;if(!video||!video.videoWidth)return;const canvas=document.createElement("canvas");const size=Math.min(video.videoWidth,video.videoHeight);canvas.width=size;canvas.height=size;const context=canvas.getContext("2d");if(!context)return;context.translate(size,0);context.scale(-1,1);context.drawImage(video,(video.videoWidth-size)/2,(video.videoHeight-size)/2,size,size,0,0,size,size);canvas.toBlob(blob=>{if(!blob)return;setPhotoUrl(URL.createObjectURL(blob));stopCamera()},"image/jpeg",.88)};
 const retakePhoto=()=>{clearPhoto();void startCamera()};
 const finishScan=()=>{clearPhoto();stopCamera();setStep(3)};
 useEffect(()=>()=>{streamRef.current?.getTracks().forEach(track=>track.stop())},[]);
 return <main>
  <header className="header"><a className="brand" href="#top"><b>D</b><span><strong>DIVA</strong><small>CLINIC</small></span></a><nav><a href="#services">Treatments</a><a href="#analysis">AI Skin Check</a><a href="#about">About</a></nav><a className="navCta" href="#booking">Book consultation</a></header>
  <section className="hero" id="top"><div><p className="eyebrow">A MORE PERSONAL KIND OF SKINCARE</p><h1>Your skin tells a story.<br/><em>Let&apos;s understand it.</em></h1><p className="lead">Discover visible skin concerns with our guided AI skin check, then connect with a Diva Clinic specialist for a treatment plan made for you.</p><div className="actions"><a className="button" href="#analysis">Start free skin check →</a><a className="link" href="#how">How it works ↘</a></div><p className="rating"><span>DS</span><span>ML</span><span>AK</span> <strong>4.9 ★</strong> Loved by 1,200+ clients</p></div><div className="heroImg"><img src="./diva-clinic-hero-v3.jpg" alt="Diva Clinic specialist consulting a client"/><aside>✦ <span><small>PERSONALIZED CARE</small><strong>Clinician-reviewed results</strong></span></aside></div></section>
  <div className="strip"><span>✦ AI-GUIDED SCREENING</span><span>✦ LICENSED SPECIALISTS</span><span>✦ KHMER & ENGLISH</span><span>✦ SECURE & PRIVATE</span></div>
  <section className="how" id="how"><header><p className="eyebrow">YOUR CONSULTATION, SIMPLIFIED</p><h2>Three thoughtful steps<br/>to your best skin.</h2></header><div className="steps"><article><i>01</i><b>◎</b><h3>Tell us about your skin</h3><p>Share your goals, routine and concerns through a short private questionnaire.</p></article><article><i>02</i><b>⌁</b><h3>Complete your skin scan</h3><p>Our guided camera helps capture clear front and side photos for cosmetic screening.</p></article><article><i>03</i><b>◷</b><h3>Meet your specialist</h3><p>Choose a recommended consultation, book a convenient time and receive expert care.</p></article></div></section>
  <section className="analysis" id="analysis"><div className="analysisCopy"><p className="eyebrow">DIVA AI SKIN ANALYSIS • DEMO</p><h2>A clearer view of<br/>what your skin needs.</h2><p>Complete this guided demo to experience the journey from cosmetic screening to a confirmed clinic appointment.</p><ul><li>✓ Takes less than 3 minutes</li><li>✓ Real camera, no app required</li><li>✓ Photo stays on your device</li></ul><div className="privacyNote"><b>⌾ PRIVATE BY DESIGN</b><span>Your photo is processed temporarily in this browser. It is never uploaded, stored, or shared.</span></div><small>Demo cosmetic screening only. This experience does not provide a medical diagnosis.</small></div>
   <div className="analyzer"><header><strong>DIVA <i>AI</i></strong><span>Step {step} of 3</span></header><div className="progress"><i style={{width:`${step*33.33}%`}}/></div>
   {step===1&&<div className="card"><p className="mini">SKIN PROFILE</p><h3>What would you like to focus on?</h3><div className="concerns">{["Acne & breakouts","Dark spots","Texture & pores","Dryness","Fine lines","Redness"].map((x,i)=><label key={x}><input type="checkbox" defaultChecked={i===1||i===2}/><span>{x}</span></label>)}</div><button onClick={()=>{clearPhoto();setStep(2)}}>Continue to guided scan →</button></div>}
   {step===2&&<div className="card cameraCard"><p className="mini">PRIVATE CAMERA CHECK</p><h3>{photoUrl?"Review your photo":"Position your face inside the guide"}</h3><div className="camera">
    {!photoUrl&&<video ref={videoRef} playsInline muted aria-label="Live front camera preview"/>}
    {photoUrl&&<img src={photoUrl} alt="Temporary camera capture preview"/>}
    {!cameraActive&&!photoUrl&&<div className="cameraPlaceholder"><b>⌾</b><span>Camera is off</span></div>}
    {cameraActive&&<div className="faceFrame" aria-hidden="true"/>}
    {cameraActive&&<span className="liveBadge">● LIVE · ON DEVICE ONLY</span>}
   </div><p className="tip">{photoUrl?"This temporary preview will be deleted when you continue or leave the page.":"Remove glasses, use natural light and keep your face relaxed."}</p>
   {cameraError&&<p className="cameraError" role="alert">{cameraError}</p>}
   {!cameraActive&&!photoUrl&&<button onClick={()=>void startCamera()}>Allow camera access</button>}
   {cameraActive&&<button onClick={capturePhoto}>Capture photo</button>}
   {photoUrl&&<div className="photoActions"><button className="retake" onClick={retakePhoto}>Retake</button><button onClick={finishScan}>Delete photo & view demo result ✦</button></div>}
   <p className="localOnly">🔒 No upload · No database · No image storage</p></div>}
   {step===3&&<div className="card"><div className="resultHead"><div><p className="mini">DEMO RESULT</p><h3>Your visible skin overview</h3></div><b>78<small>/100</small></b></div><div className="findings">{findings.map(([label,value])=><div key={label}><p><span>{label}</span><strong>{value}%</strong></p><div><i style={{width:`${value}%`}}/></div></div>)}</div><aside className="recommend">✦ <span><small>RECOMMENDED NEXT STEP</small><strong>Personal Skin Consultation</strong>30 minutes · In-clinic or online</span></aside><a className="button" href="#booking">Choose appointment time →</a></div>}</div>
  </section>
  <section className="booking" id="booking"><header><p className="eyebrow">YOUR NEXT STEP</p><h2>Reserve your consultation.</h2><p>Select a convenient appointment. Our team will confirm the details with you directly.</p></header><div className="bookingBox">{!booked?<><aside className="service"><p className="mini">SELECTED SERVICE</p><h3>Personal Skin Consultation</h3><p>One-on-one skin assessment with a Diva Clinic specialist.</p><div>◷ 30 minutes<br/>⌖ Diva Clinic Phnom Penh</div><strong>Consultation fee confirmed by clinic</strong></aside><div className="schedule"><div className="month"><button>‹</button><strong>August 2026</strong><button>›</button></div><div className="dates">{[["MON","24"],["TUE","25"],["WED","26"],["THU","27"],["FRI","28"]].map(([d,n],i)=><button className={i===1?"active":""} key={n}><small>{d}</small><strong>{n}</strong></button>)}</div><p className="mini">AVAILABLE TIMES</p><div className="times">{["9:00 AM","10:30 AM","1:00 PM","3:30 PM","5:00 PM"].map(x=><button className={time===x?"active":""} onClick={()=>setTime(x)} key={x}>{x}</button>)}</div><button className="confirm" onClick={()=>setBooked(true)}>Confirm appointment →</button></div></>:<div className="success"><b>✓</b><p className="eyebrow">APPOINTMENT REQUESTED</p><h3>Thank you, your time is reserved.</h3><p>Tuesday, 25 August 2026 at {time}<br/>Diva Clinic Phnom Penh</p><button onClick={()=>setBooked(false)}>Change appointment</button></div>}</div></section>
  <section className="services" id="services"><div><p className="eyebrow">CURATED FOR YOUR SKIN</p><h2>Care that goes deeper<br/>than the surface.</h2></div><div>{[["01","Advanced Facial Care","Personalized treatments designed around your skin's current needs."],["02","Brightening Programs","Clinician-guided care for a more even, luminous complexion."],["03","Acne & Texture Care","Thoughtful programs to support clearer, smoother-looking skin."]].map(x=><article key={x[0]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <footer id="about"><div className="footBrand"><b>D</b><span><strong>DIVA CLINIC</strong><p>Modern skin care, thoughtfully personal.</p></span></div><div><strong>VISIT US</strong><p>Phnom Penh, Cambodia<br/>Open daily · 9 AM–7 PM</p></div><div><strong>CONTACT</strong><p>WhatsApp · Telegram<br/>Facebook · Instagram</p></div><small>© 2026 Diva Clinic. Demo concept.</small></footer>
 </main>
}
